### PR TITLE
Allow `buttons` prop to be passed to custom ui

### PR DESCRIPTION
**Pull request by netemmajones**

### CODE REVIEW

**Comment by usamamashkoor** [comment]
Did you find any solution to this...?

**Comment by netemmajones** [comment]
> Did you find any solution to this...?

Yep, just needed to pass `buttons` to  `dataCustomUI` in `renderCustomUI`.

**Comment by usamamashkoor** [comment]
@netemmajones Thanks for your reply can you please share a rough example please i am new to react so it would be a great help.

**Comment by netemmajones** [comment]
> @netemmajones Thanks for your reply can you please share a rough example please i am new to react so it would be a great help.

See https://github.com/GA-MO/react-confirm-alert/pull/34/files. Feel free to install use my fork which has the changes needed https://github.com/netemmajones/react-confirm-alert

**Comment by usamamashkoor** [comment]
Thanks

**Pull request merged**
